local PLUGIN = PLUGIN
net.Receive("ui_dealership", function(len, ply)
    nut.dialog.Generate("Paul McCormick", "models/player/breen.mdl", "Car Salesman", "Berlin Motors", function(ply)
        nut.dialog.frame("Paul McCormick", "models/player/breen.mdl", "Car Salesman", "Berlin Motors")
        nut.dialog.text("Ay pal, welcome to Berlin Motors, what can I do for ya?")
        nut.dialog.button("Nothing, just looking around.", 40, function() self:Remove() end)
        nut.dialog.button("I'd like to spawn my vehicle.", 40, function()
            self:Remove()
            nut.dialog.frame("Paul McCormick", "models/player/breen.mdl", "Car Salesman", "Berlin Motors")
            nut.dialog.text("Go to any Berlin garage around the city, there\n you can store and retrieve your vehicle.")
            nut.dialog.button("Okay, thank you.", 40, function() self:Remove() end)
        end)

        nut.dialog.button("I'd like to buy/sell/test drive a vehicle.", 40, function()
            self:Remove()
            nut.dialog.frame("Paul McCormick", "models/player/breen.mdl", "Car Salesman", "Berlin Motors")
            nut.dialog.text("What kind of vehicle you interested in?")
            for k, v in pairs(PLUGIN.VehicleCategories) do
                nut.dialog.button(v, 40, function()
                    self:Remove()
                    VehicleList(v)
                end)
            end
        end)
    end)

    function VehicleList(category)
        dframe = vgui.Create("DFrame")
        dframe:SetTitle("Berlin Motors - " .. category)
        dframe:SetSize(ScrW() - 450, ScrH() - 350)
        dframe:Center()
        dframe:MakePopup()
        dframe:ShowCloseButton(true)
        dframe.scroll = vgui.Create("DScrollPanel", dframe)
        dframe.scroll:Dock(FILL)
        dframe.category = dframe.scroll:Add("DCollapsibleCategory")
        dframe.category:SetLabel(category)
        dframe.category:Dock(TOP)
        dframe.category:SetExpanded(1)
        dframe.category.Paint = function(dframe, w, h) dframe:SetBGColor(Color(0, 0, 0, 1)) end
        dframe.category.panel = vgui.Create("DPanel", dframe.category)
        dframe.category.panel:Dock(FILL)
        dframe.category.list = vgui.Create("DListLayout", dframe.category.panel)
        dframe.category.list:Dock(FILL)
        dframe.category.list:DockPadding(3, 3, 3, 3)
        dframe.category:SetContents(dframe.category.list)
        dframe.scroll:AddItem(dframe.category)
        for k, v in pairs(PLUGIN.Vehicles) do
            if v.Category == category then
                dframe.item = dframe.category.list:Add("DPanel")
                dframe.item:SetTall(70)
                dframe.spawnIcon = vgui.Create("nutSpawnIcon", dframe.item)
                dframe.spawnIcon:Dock(LEFT)
                dframe.spawnIcon:SetSize(48, 48)
                dframe.spawnIcon:SetModel(v.Model)
                dframe.name = vgui.Create("DLabel", dframe.item)
                dframe.name:SetPos(56, 25)
                dframe.name:SetFont("Title_Font")
                dframe.name:SetText(v.Name)
                dframe.name:SizeToContents()
                dframe.buyBox = vgui.Create("DPanel", dframe.item)
                dframe.buyBox:Dock(RIGHT)
                dframe.buyBox:DockMargin(1, 1, 1, 1)
                dframe.buyBox:SetWide(90)
                dframe.buyBox:SetPaintBackground(false)
                dframe.price = vgui.Create("DButton", dframe.buyBox)
                dframe.price:Dock(TOP)
                dframe.price:SetText("$" .. (v.Price or 50))
                dframe.price:SetTooltip("Tax: %" .. PLUGIN.VehicleTax)
                dframe.price:SetFont("Price_Font")
                dframe.price:SetTextColor(Color(125, 125, 125, 225))
                dframe.price:DockMargin(0, 5, 5, 0)
                dframe.price:SetPaintBackground(false)
                dframe.buy = vgui.Create("DButton", dframe.buyBox)
                dframe.buy:Dock(BOTTOM)
                dframe.buy:DockMargin(0, 0, 5, 3)
                dframe.buy:SetSize(100, 35)
                dframe.buy:SetText("Options")
                dframe.buy.DoClick = function()
                    Derma_Query("Selection one of the following actions:", "Vehicle Options", "Buy + (" .. (PLUGIN.VehicleTax * 100) .. "% Vehicle Tax)", function()
                        net.Start("buy_vehicle")
                        net.WriteString(k)
                        net.SendToServer()
                    end, "Sell", function()
                        net.Start("sell_vehicle")
                        net.WriteString(k)
                        net.SendToServer()
                    end, "Test Drive", function()
                        net.Start("testdrive_vehicle")
                        net.WriteString(k)
                        net.SendToServer()
                    end)
                end
            end
        end
    end
end)

net.Receive("garage_ui", function(len, ply)
    local entity = net.ReadEntity()
    dframe = vgui.Create("DFrame")
    dframe:SetTitle("Jackson Autos")
    dframe:SetSize(300, 130)
    dframe:Center()
    dframe:MakePopup()
    dframe.button = vgui.Create("DButton", dframe)
    dframe.button:SetText("Spawn or Return Vehicle")
    dframe.button:SetTall(50)
    dframe.button:Dock(TOP)
    dframe.button:SetTextColor(Color(255, 255, 255, 255))
    dframe.button.DoClick = function()
        dframe:Remove()
        dframe = vgui.Create("DFrame")
        dframe:SetTitle("Purchased Vehicles")
        dframe:SetSize(ScrW() - 450, ScrH() - 350)
        dframe:Center()
        dframe:MakePopup()
        dframe:ShowCloseButton(true)
        dframe.scroll = vgui.Create("DScrollPanel", dframe)
        dframe.scroll:Dock(FILL)
        dframe.category = dframe.scroll:Add("DCollapsibleCategory")
        dframe.category:SetLabel("Vehicles")
        dframe.category:Dock(TOP)
        dframe.category:SetExpanded(1)
        dframe.category.Paint = function(dframe, w, h) dframe:SetBGColor(Color(0, 0, 0, 1)) end
        dframe.category.panel = vgui.Create("DPanel", dframe.category)
        dframe.category.panel:Dock(FILL)
        dframe.category.list = vgui.Create("DListLayout", dframe.category.panel)
        dframe.category.list:Dock(FILL)
        dframe.category.list:DockPadding(3, 3, 3, 3)
        dframe.category:SetContents(dframe.category.list)
        dframe.scroll:AddItem(dframe.category)
        for k, v in pairs(PLUGIN.Vehicles) do
            if LocalPlayer():getChar():getData(v.Identifier, false) then
                dframe.item = dframe.category.list:Add("DPanel")
                dframe.item:SetTall(70)
                dframe.spawnIcon = vgui.Create("nutSpawnIcon", dframe.item)
                dframe.spawnIcon:Dock(LEFT)
                dframe.spawnIcon:SetSize(48, 48)
                dframe.spawnIcon:SetModel(v.Model)
                dframe.name = vgui.Create("DLabel", dframe.item)
                dframe.name:SetPos(56, 25)
                dframe.name:SetFont("Title_Font")
                dframe.name:SetText(v.Name)
                dframe.name:SizeToContents()
                dframe.buyBox = vgui.Create("DPanel", dframe.item)
                dframe.buyBox:Dock(RIGHT)
                dframe.buyBox:DockMargin(1, 1, 1, 1)
                dframe.buyBox:SetWide(90)
                dframe.buyBox:SetPaintBackground(false)
                dframe.buy = vgui.Create("DButton", dframe.buyBox)
                dframe.buy:Dock(BOTTOM)
                dframe.buy:DockMargin(0, 0, 5, 3)
                dframe.buy:SetSize(100, 30)
                dframe.buy:SetText("Spawn")
                dframe.buy.DoClick = function()
                    net.Start("spawn_vehicle")
                    net.WriteString(v.Identifier)
                    net.WriteString(v.Name)
                    net.WriteColor(Color(255, 255, 255, 255))
                    net.WriteEntity(entity)
                    net.SendToServer()
                    print(entity)
                end

                dframe.returnn = vgui.Create("DButton", dframe.buyBox)
                dframe.returnn:Dock(BOTTOM)
                dframe.returnn:DockMargin(0, 0, 5, 3)
                dframe.returnn:SetSize(100, 30)
                dframe.returnn:SetText("Return")
                dframe.returnn.DoClick = function()
                    net.Start("return_vehicle")
                    net.WriteString(v.Identifier)
                    net.WriteString(v.Name)
                    net.SendToServer()
                    print(entity)
                end
            end
        end
    end

    dframe.button = vgui.Create("DButton", dframe)
    if PLUGIN.VehicleRepairEnabled then
        dframe.button:SetText("Modify & Spawn / Repair Vehicle")
    else
        dframe.button:SetText("Modify & Spawn Vehicle")
    end

    dframe.button:SetTall(50)
    dframe.button:Dock(TOP)
    dframe.button:SetTextColor(Color(255, 255, 255, 255))
    dframe.button.DoClick = function()
        dframe:Remove()
        dframe = vgui.Create("DFrame")
        dframe:SetTitle("Jackson Autos - Modification Options")
        if PLUGIN.VehicleRepairEnabled then
            dframe:SetSize(300, 185)
        else
            dframe:SetSize(300, 130)
        end

        dframe:Center()
        dframe:MakePopup()
        dframe.button = vgui.Create("DButton", dframe)
        dframe.button:SetText("Paint Job")
        dframe.button:SetTall(50)
        dframe.button:Dock(TOP)
        dframe.button:SetTextColor(Color(255, 255, 255, 255))
        dframe.button.DoClick = function()
            dframe:Remove()
            dframe = vgui.Create("DFrame")
            dframe:SetTitle("Purchased Vehicles")
            dframe:SetSize(ScrW() - 450, ScrH() - 350)
            dframe:Center()
            dframe:MakePopup()
            dframe:ShowCloseButton(true)
            dframe.scroll = vgui.Create("DScrollPanel", dframe)
            dframe.scroll:Dock(FILL)
            dframe.category = dframe.scroll:Add("DCollapsibleCategory")
            dframe.category:SetLabel("Vehicles")
            dframe.category:Dock(TOP)
            dframe.category:SetExpanded(1)
            dframe.category.Paint = function(dframe, w, h) dframe:SetBGColor(Color(0, 0, 0, 1)) end
            dframe.category.panel = vgui.Create("DPanel", dframe.category)
            dframe.category.panel:Dock(FILL)
            dframe.category.list = vgui.Create("DListLayout", dframe.category.panel)
            dframe.category.list:Dock(FILL)
            dframe.category.list:DockPadding(3, 3, 3, 3)
            dframe.category:SetContents(dframe.category.list)
            dframe.scroll:AddItem(dframe.category)
            for k, v in pairs(PLUGIN.Vehicles) do
                if LocalPlayer():getChar():getData(v.Identifier, false) then
                    dframe.item = dframe.category.list:Add("DPanel")
                    dframe.item:SetTall(70)
                    dframe.spawnIcon = vgui.Create("nutSpawnIcon", dframe.item)
                    dframe.spawnIcon:Dock(LEFT)
                    dframe.spawnIcon:SetSize(48, 48)
                    dframe.spawnIcon:SetModel(v.Model)
                    dframe.name = vgui.Create("DLabel", dframe.item)
                    dframe.name:SetPos(56, 25)
                    dframe.name:SetFont("Title_Font")
                    dframe.name:SetText(v.Name)
                    dframe.name:SizeToContents()
                    dframe.buyBox = vgui.Create("DPanel", dframe.item)
                    dframe.buyBox:Dock(RIGHT)
                    dframe.buyBox:DockMargin(1, 1, 1, 1)
                    dframe.buyBox:SetWide(90)
                    dframe.buyBox:SetPaintBackground(false)
                    dframe.buy = vgui.Create("DButton", dframe.buyBox)
                    dframe.buy:Dock(BOTTOM)
                    dframe.buy:DockMargin(0, 0, 5, 3)
                    dframe.buy:SetSize(100, 60)
                    dframe.buy:SetText("Paint")
                    dframe.buy.DoClick = function()
                        dframe:Remove()
                        local Frame = vgui.Create("DFrame")
                        Frame:SetTitle("Color Options")
                        Frame:SetSize(450, 310)
                        Frame:Center()
                        Frame:MakePopup()
                        local Mixer = vgui.Create("DColorMixer", Frame)
                        Mixer:Dock(TOP)
                        Mixer:SetPalette(false)
                        Mixer:SetAlphaBar(false)
                        Mixer:SetWangs(false)
                        Mixer:SetColor(Color(30, 100, 160))
                        Mixer.ValueChanged = function(pnl, col) MixerCurrentColor = Color(col.r, col.g, col.b, 255) end
                        local Submit = vgui.Create("DButton", Frame)
                        Submit:SetTall(48)
                        Submit:SetText("Spawn Vehicle")
                        Submit:Dock(BOTTOM)
                        Submit.DoClick = function()
                            Frame:Close()
                            net.Start("spawn_vehicle")
                            net.WriteString(v.Identifier)
                            net.WriteString(v.Name)
                            net.WriteColor(MixerCurrentColor)
                            net.WriteEntity(entity)
                            net.SendToServer()
                        end
                    end
                end
            end
        end

        dframe.button = vgui.Create("DButton", dframe)
        dframe.button:SetText("Engine Mods")
        dframe.button:SetTall(50)
        dframe.button:SetDisabled(true)
        dframe.button:Dock(TOP)
        dframe.button:SetTextColor(Color(255, 255, 255, 255))
        dframe.button.DoClick = function() end
        if PLUGIN.VehicleRepairEnabled then
            dframe.button = vgui.Create("DButton", dframe)
            dframe.button:SetText("Repair Vehicle ($" .. PLUGIN.VehicleRepairCost .. ")")
            dframe.button:SetTall(50)
            dframe.button:Dock(TOP)
            dframe.button:SetTextColor(Color(255, 255, 255, 255))
            dframe.button.DoClick = function()
                net.Start("repair_vehicle")
                net.SendToServer()
            end
        end
    end
end)