-- Schema info
SCHEMA.name = "Red Panda Gaming"
SCHEMA.author = "Dave01 & Jeb004"
SCHEMA.desc = "WORLD WAR 2 ROLEPLAY COMMUNITY"
nut.currency.set("", "Reichsmark", "Reichsmarks")
nut.util.include( "sv_hooks.lua" )

-- Remove typing indicator (TESTING)
if CLIENT then
	hook.Add("InitPostEntity", "RemoveChatBubble", function()
		hook.Remove("StartChat", "StartChatIndicator")
		hook.Remove("FinishChat", "EndChatIndicator")

		hook.Remove("PostPlayerDraw", "DarkRP_ChatIndicator")
		hook.Remove("CreateClientsideRagdoll", "DarkRP_ChatIndicator")
		hook.Remove("player_disconnect", "DarkRP_ChatIndicator")
	end)
end

-- Disable Crosshair
hook.Add('ShouldDrawCrosshair', 'DisableCrosshair', function()
	return false
end)

-- Disable Raised Weapons
hook.Add("PluginShouldLoad", "removeRaiseWeapons", function(uniqueID)
	if uniqueID == "raiseweapons" then return false end
end)

-- Staff Faction Recognition
function SCHEMA:IsCharRecognized(char, id)
	if char:getFaction() == FACTION_STAFF then
		return true
	end
end

-- Dice Roll
nut.command.add("roll", {
	syntax = "[number maximum]",
	onRun = function(client, arguments)
		local outOf = tonumber(arguments[1]) or 100

		nut.chat.send(client, "roll", math.random(0, math.min(outOf, 100)).."/"..outOf)
	end
})

-- Grab Player Models
nut.command.add("chargetmodel", {
    syntax = "<string name>",
    onRun = function(client, arguments)
		
        local target = nut.command.findPlayer(client, arguments[1])

        if (IsValid(target) and target:getChar()) then
            client:notify("You have copied the model '"..target:GetModel().."' to your clipboard.")
            netstream.Start(client, "sendToClipboard", target:GetModel())
        end
    end
})

-- Find Flags
nut.command.add("findallflags", {
    adminOnly = true,
    onRun = function(client, arguments)
        for k, v in pairs(player.GetAll()) do
            if IsValid(v) then
                if (v:getChar():getFlags() == "") then continue end
                client:ChatPrint(v:Name() .. " — " .. v:getChar():getFlags())
            end
        end
    end
})

-- Check Money
nut.command.add("checkallmoney", {
    adminOnly = true,
    syntax = "<string charname>",
    onRun = function(client, arguments)
        for k, v in pairs(player.GetAll()) do
            if v:getChar() then
                client:ChatPrint("Red Panda Gaming | ".. v:Name() .. " has " .. v:getChar():getMoney() .. " Reichsmarks")
            end
        end
    end
})

-- Check Inventory
nut.command.add("checkinventory", {
    adminOnly = true,
    syntax = "<string target>",
    onRun = function(client, arguments)
        local target = nut.command.findPlayer(client, arguments[1])

        if (IsValid(target) and target:getChar() and target ~= client) then
            local inventory = target:getChar():getInv()
            inventory:addAccessRule(ItemCanEnterForEveryone, 1)
            inventory:addAccessRule(CanReplicateItemsForEveryone, 1)
            inventory:sync(client)
            net.Start("OpenInvMenu")
            net.WriteEntity(target)
            net.WriteType(inventory:getID())
            net.Send(client)
        elseif (target == client) then
            client:notifyLocalized("You cannot use this command on yourself")
        end
    end
})

nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock01.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock02.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock03.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock04.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock05.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/admiralfrock06.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/admirals/strassefrock.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock01.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock02.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock03.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock04.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock05.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/juniorofficers/juniorofficerfrock06.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock01.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock02.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock03.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock04.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock05.mdl", "player")
nut.anim.setModelClass("models/rpg/frock/seniorofficers/seniorofficerfrock06.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/gd/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/panzerwaffe/co/wehr_co.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/panzerwaffe/en/wehr_en.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/panzerwaffe/nco/wehr_nco.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/brotleathercoat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co1_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co2_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co3_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co4_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co5_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/co6_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en1_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en2_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en3_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en4_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en5_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/en6_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco1_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco2_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco3_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco4_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco5_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/nco6_coat.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/rm6.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/rm6fat.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/rm6normal.mdl", "player")
nut.anim.setModelClass("models/rpg/luftwaffe/coat/rm6.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine01.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine02.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine03.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine04.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine05.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/chief/chiefmarine06.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine01.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine02.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine03.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine04.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine05.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/juniorofficers/juniorofficermarine06.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine01.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine02.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine03.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine04.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine05.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/po/pomarine06.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine01.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine02.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine03.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine04.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine05.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/sailor/marine06.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine01.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine02.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine03.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine04.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine05.mdl", "player")
nut.anim.setModelClass("models/rpg/marines/seniorofficers/seniorofficermarine06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/admiralsea06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/admirals/strassesea.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/chief/chiefsea06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/juniorofficers/juniorofficersea06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/midshipman/midshipman06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/po/posea06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/sailor/sailor06.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea01.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea02.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea03.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea04.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea05.mdl", "player")
nut.anim.setModelClass("models/rpg/seaservice/seniorofficers/seniorofficersea06.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/robber_tuckedtie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/robber_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/robber_shirt_2.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/robber_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/robber_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_10_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_09_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_08_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_07_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_06_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_05_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_04_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_03_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_02_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_shirt_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_shirt.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_open.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/suits/male_01_closed_coat_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat6.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat5.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat4.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat3.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat2.mdl", "player")
nut.anim.setModelClass("models/rpg/sssuits/gspcoat1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/sd/closecollargo6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_10_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_10_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_10_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_10_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_09_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_09_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_09_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_09_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_08_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_08_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_08_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_08_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_07_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_07_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_07_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_07_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_06_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_06_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_06_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_06_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_05_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_05_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_05_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_05_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_04_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_04_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_04_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_04_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_02_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_02_open_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_02_open.mdl", "player")
nut.anim.setModelClass("models/rpg/armbandsuits/male_02_closed_tie.mdl", "player")
nut.anim.setModelClass("models/rpg/virusss.mdl", "player")
nut.anim.setModelClass("models/rpg/virusnsdap.mdl", "player")
nut.anim.setModelClass("models/rpg/omninsdap.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe06.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe05.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe04.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe03.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe02.mdl", "player")
nut.anim.setModelClass("models/rpg/gerichtrobe01.mdl", "player")
nut.anim.setModelClass("models/rpg/baumernsdap.mdl", "player")
nut.anim.setModelClass("models/rpg/baumermodel.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_11.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_10.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_06.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_04.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_02.mdl", "player")
nut.anim.setModelClass("models/rpg/dresses/female_01.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_11_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_11.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_10_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_10.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_09.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_08.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_07.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_06_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_06.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_05_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_05.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_04.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_03.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_02.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/male_01.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_07_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_07_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_07_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_07.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_06_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_06_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_06_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_06.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_04_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_04_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_04_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_04.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_03_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_03_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_03_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_03.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_02_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_02_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_02_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_02.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_01_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_01_b_extended.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_01_b.mdl", "player")
nut.anim.setModelClass("models/rpg/citizens/female_01.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka6.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka5.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka4.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka3.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka2.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/kharkovparka1.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/cbearedits/waffenss/infantry/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/officer_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/lower_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/sa/generalofficer_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/lower_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/higher_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration_coat6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration_coat3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattipm0v3edits/nsdap/reichsleitung/command_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_06.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_05.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_04.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_03.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_02.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_01.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_06.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_05.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_04.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_03.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_02.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_01.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_06.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_05.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_04.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_03.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_02.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_01.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_06.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_05.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_04.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_03.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_02.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/pm0v3/deutsche_beamten/lowerservice_01.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/mattimodels/orpo/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/feld/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/rf6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/rf4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/baseline/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/nco1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/go1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/en1.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/drachengruppe06.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co6.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co5.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co4.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co3.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co2.mdl", "player")
nut.anim.setModelClass("models/rpg/ss/1stssvt/co1.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco6.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco5.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco4.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco3.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco2.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radnco1.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo6.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo5.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo4.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo3.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo2.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radgo1.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted6.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted5.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted4.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted3.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted2.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radenlisted1.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco6.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco5.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco4.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco3.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco2.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radco1.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted6.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted5.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted4.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted3.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted2.mdl", "player")
nut.anim.setModelClass("models/rpg/rad/radcloseenlisted1.mdl", "player")
nut.anim.setModelClass("models/rpg/virusnsdap.mdl", "player")
nut.anim.setModelClass("models/rpg/heer/wehrkreisiii/brotleathercoat.mdl", "player")
nut.anim.setModelClass("models/genwolf/obn/reichsmarschall.mdl", "player")
nut.anim.setModelClass("models/keitel/comradebear/pm0v3/player/heer/colorable/gen/m38_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/heer/infantry/gen/m38_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/heer/infantry/gen/m38_s1_05.mdl", "player")
nut.anim.setModelClass("models/minus/fuhrer/hilter.mdl", "player")
nut.anim.setModelClass("models/greaterempire/leader.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/nco/39/m32_nco1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/go/39/m32_go1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/go/39/m32_go3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/go/39/m32_go4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/go/39/m32_go4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/go/39/m32_go4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/co/39/m32_co1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/ss/beltless/co/39/m32_co1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/nco/39/m32_nco1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/go/39/m32_go6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/go/39/m32_go5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/co/39/m32_co1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/co/39/m32_co2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/co/39/m32_co3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/co/39/m32_co4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/co/39/m32_co5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en1.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en4.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en5.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/en/39/m32_en6.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/go/39/m32_go2.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/go/39/m32_go3.mdl", "player")
nut.anim.setModelClass("models/theis/germ/sd/go/39/m32_go4.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/command_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/higher_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lower_administration6.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration1.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration2.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration3.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration4.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration5.mdl", "player")
nut.anim.setModelClass("models/rpg/kaiserparty/lowersenior_administration6.mdl", "player")
nut.anim.setModelClass("models/ibz/luftwaffe/airborn/ger_para_06.mdl", "player")
nut.anim.setModelClass("models/ibz/luftwaffe/airborn/ger_para_06_a.mdl", "player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_01.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_02.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_03.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_04.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_05.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/enlisted/reichsheer_enlisted_service_06.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_01.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_02.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_03.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_04.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_05.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/general/reichsheer_general_service_06.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_01.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_02.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_03.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_04.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_05.mdl","player")
nut.anim.setModelClass("models/strabe/interwar/reichswehr/heer/service/officer/reichsheer_officer_service_06.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_01.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_02.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_03.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_04.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_05.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/reichservice_06.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_01.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_02.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_03.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_04.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_05.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/seniorservice_06.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_01.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_02.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_03.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_04.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_05.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/deutsche_beamten/upperservice_06.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_01.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_02.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_03.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_04.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_05.mdl","player")
nut.anim.setModelClass("models/brot/rpg/mattimodels/pm0v3/frankreich_beamten/lowerservice_06.mdl","player")
nut.anim.setModelClass("models/rpg/rosenguarde/go6.mdl","player")
nut.anim.setModelClass("models/rpg/rosenguarde/co6.mdl","player")
nut.anim.setModelClass("models/rpg/rosenguarde/nco6.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_01.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_02.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_04.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_06.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_10.mdl","player")
nut.anim.setModelClass("models/rpg/dresses/female_11.mdl","player")
nut.anim.setModelClass("models/historia/kaput.mdl","player")
nut.anim.setModelClass("models/historia/ludvigss.mdl","player")
nut.anim.setModelClass("models/brot/rpg/sssuits/gspcoat6.mdl","player")
nut.anim.setModelClass("","player")

local STAFFROLES = {
	superadmin = true,
	root = true,
	superadministrator = true,
	senioradministrator = true,
	administrator = true,
	moderator = true,
	gamemaster = true,
}

nut.chat.register("sc", {
	onCanSay =  function(speaker, text)
		if(!STAFFROLES[speaker:GetUserGroup()]) then
			speaker:notify("You do not have the permissions to do this.")
			return false 
		end
		if(STAFFROLES[speaker:GetUserGroup()]) then
			return true
		end
	end,
	
	onChatAdd = function(speaker, text)
		chat.AddText(Color(78, 205, 64), "STAFF/GAMEMASTER CHAT", Color(255, 255, 255), " | ", team.GetColor(speaker:Team()), speaker:steamName() .. ": ",  color_white, text)
	end,
	onCanHear = function(speaker, listener)
	if(STAFFROLES[listener:GetUserGroup()]) then
		return true else return false
	end
	end,
	prefix = {"/sc"},
	noSpaceAfter = true,
	filter = "OOC"
})

